CREATE TABLE lesson
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number INTEGER                                 NOT NULL,
    CONSTRAINT pk_lesson PRIMARY KEY (id)
);

CREATE TABLE mission
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title                VARCHAR(255),
    challenge            BOOLEAN                                 NOT NULL,
    lesson_id            BIGINT,
    description_markdown TEXT,
    CONSTRAINT pk_mission PRIMARY KEY (id)
);

CREATE TABLE submission
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT,
    mission_id   BIGINT,
    attempt      INTEGER                                 NOT NULL,
    passed       BOOLEAN                                 NOT NULL,
    output       VARCHAR(255),
    code         TEXT,
    submitted_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_submission PRIMARY KEY (id)
);

CREATE TABLE test_case
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mission_id      BIGINT,
    input           TEXT,
    expected_output TEXT,
    CONSTRAINT pk_testcase PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    password   VARCHAR(255),
    email      VARCHAR(255)                            NOT NULL,
    avatar_url VARCHAR(255),
    role       VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE mission
    ADD CONSTRAINT FK_MISSION_ON_LESSON FOREIGN KEY (lesson_id) REFERENCES lesson (id);

ALTER TABLE submission
    ADD CONSTRAINT FK_SUBMISSION_ON_MISSION FOREIGN KEY (mission_id) REFERENCES mission (id);

ALTER TABLE submission
    ADD CONSTRAINT FK_SUBMISSION_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE test_case
    ADD CONSTRAINT FK_TESTCASE_ON_MISSION FOREIGN KEY (mission_id) REFERENCES mission (id);